name: Deploy to gh-pages

on:
  push:
    branches: 
      - master

jobs:
  built-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: |
          npm install
          npm run build --if-present
          npm test
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with: 
          target-branch: gh-pages
          build-dir: build
        env: 
          GITHUB_TOKEN: ${{ secrets.TEST_REPO_TOKEN }}